<div class="fixed contain-to-grid">
	<nav class="top-bar" data-topbar>

		<section class="top-bar-section">
			<!-- Right Nav Section -->
			<ul class="right">				
				<li class="has-dropdown">
					<a href="">Resources</a>
					<ul class="dropdown">
						<li><a target=_blank href="http://www.rcsb.org/pdb/home/home.do">Protein Data Bank</a></li>
						<li><a target=_blank href="http://hmmer.janelia.org/">HMMER</a></li>
					</ul>
				</li>
				<li class="has-dropdown">
					<a href="">CS @ WWU</a>
					<ul class="dropdown">
						<li><a target=_blank href="https://cst.wwu.edu/computer-science">WWU CS Home</a></li>
						<li><a target=_blank href="http://support.cs.wwu.edu/index.php/Main_Page">CS Support</a></li>
						<li><a target=_blank href="http://sw.cs.wwu.edu/~nordwap/index.php">Web Cams</a></li>
						<li><a target=_blank href="http://sw.cs.wwu.edu/~fugiera/dev/labStat2.php">Lab Stats</a></li>
						<li><a target=_blank href="http://acm.wwu.edu/">ACM</a></li>
						<li><a target=_blank href="http://awc.cs.wwu.edu/">AWC</a></li>
					</ul>
				</li>
			</ul>

			<!-- Left Nav Section -->
			<ul class="left">
				<li class="active"><a class="top-btn" data-target="home">Home</a></li>
				<li><a class="top-btn" data-target="raw_data">Raw Data</a></li>
				<li><a class="top-btn" data-target="about">About</a></li>
				<li><a class="top-btn" data-target="videos">Videos</a></li>
			</ul>
		</section>
	</nav>
</div>